### ISSUE TITLE
Code isn't clear about what the license is

### ISSUE THREAD

**Issue by dargo600** [boundarydevices/devregs#7]
I'm assuming this is licensed with GPL-2 not GPL-1 but as both licenses are here I'm not too sure which it is...  

I'm guessing GPLv2 as I'm unclear if GPL-1 is compatible with GPLv2.

I realize that the license is somewhat suggested to be GPL-2 on the right side but saying specifically what it is in source would be better.

**Comment by gibsson** [comment]
Sorry for the delay, after checking with both Troy & Eric, the GPL-1.0 file was clearly a mistake. The license is GPLv2 so I removed the GPL-1.0 file to avoid any further confusion.
Let me know if you have any other question.
